### ISSUE TITLE
Suggested actions not working

### ISSUE THREAD

**Issue by jasonabradley** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#1]
The suggested actions are not populating in the demo even when causing the sample utterances to appear in the transcription. Browser: Chrome 75

**Comment by efh365** [comment]
Thanks for bringing this to our attention. I will look into it. Can you verify that the words picked out by Comprehend are an *exact* match. (ex: "a new service" != "new service")? Also, are there any errors in the console?

**Comment by jasonabradley** [comment]
Yes they are exact. No errors in console. It works in Firefox sporadically, not consistently. Never works in Chrome.

Jason
________________________________

**Comment by efh365** [comment]
Can you add a screen shot or the exact text of what the translation shows and which AWS Comprehend key phrases are picked out? The suggested next steps are based on key phrases picked out by AWS Comprehend. So if you say "I would like the promotional pricing", but the key phrase is only "promotional pricing" (without "the"), then the suggested action will not appear.

I tested with a new stack in Chrome 75.0 in IAD and cannot reproduce this.
