### ISSUE TITLE
Transcription very slow

### ISSUE THREAD

**Issue by vidhanbagdai** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#10]
There is a delay of almost 6-7 seconds between what I speak and the real time transcription that happens, i.e. the text comes up on screen after 6-7 seconds after I finish speaking. The network speed is almost 100 mbps, still this issue occurs.

**Comment by tamdilip** [comment]
Yes the transcription latency is high 😐 !!

**Comment by vidhanbagdai** [comment]
Yes I know! It is impossible to showcase this to potential clients.

**Comment by vidhanbagdai** [comment]
Does anyone have a sloution for this?

**Comment by cwwiser** [comment]
Hi, might I suggest tuning your lambdas- I added memory to the real-time lambdas and see fantastic performance in my environment. Also, 100mbps is a measure of bandwidth, not an indication of network latency..

**Comment by vidhanbagdai** [comment]
@cx-cwiser Tried increasing the memory of lambdas, the transcribed text is coming up quicker on screen but still there is a gap of 5-6 seconds between what the customer speaks and the writing of the transcribed text. Any other suggeestioin or perhaps how much memory to assign to each lambda?

**Comment by laimonassutkus** [comment]
Its due to the Comprehend/Transcribe service itself. Deal with it. If you want something fast use WEB Speech API.

**Comment by efh365** [comment]
You can also try to keep your KVSTranscriber Lambda function warm by following this blog: https://aws.amazon.com/blogs/compute/new-for-aws-lambda-predictable-start-up-times-with-provisioned-concurrency/

You will need to update the KVSTrigger function to call the pre-warmed version of the function

**Comment by khastation** [comment]
@vidhanbagdai are you still facing this issue?
