### ISSUE TITLE
Event handler failed on AgentUI page

### ISSUE THREAD

**Issue by OliviaChaudhuri** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#12]
The whole flow remains untouched. Only changes are being made on AgentUI page to call certain APIs. Everything was working completely fine until yesterday afternoon. Suddenly the last bit stopped working on its own. Attaching screenshot of AgentUI backend console screen.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60867492/81770892-2f56a400-94ff-11ea-8a5d-28dd43615105.png)

**Comment by efh365** [comment]
Hi Olivia. It is hard to say why this failing with the provided information. You said everything worked fine until one afternoon. What changes did you make? Can you include a screen shot of the logs with the first error message you see? The first error, not the last one, is the most important one

**Comment by OliviaChaudhuri** [comment]
Hi

After hours of debugging we are guessing that the "Start media Streaming" block isn't passing the required data to the Lambda function that follows it. Because of which transcript is not coming.

**Comment by efh365** [comment]
Can you elaborate on what you mean by the 'required data'? What is it missing?

Do you have the contact attribute for transcription set to true?
