### ISSUE TITLE
Connect login popup shows "Session Expired"

### ISSUE THREAD

**Issue by drewdresser** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#13]
I follow the steps in the deployment guide (unless I missed something). I open up the web app, but when i get the authentication popup from Connect, I get a "Session Expired Your session has expired. Please log in." 

This happens if I'm logged into Connect on another tab or not. 

Could this be related to the new version of connecting to Connect?

**Comment by ramprasadsv** [comment]
Hello, 
     Can you please confirm if you are using SSO (SAML type of authentication) or Amazon Connect as the identity store and authentication to sign in?

**Comment by drewdresser** [comment]
Hi, thanks for the response.
I am using Amazon Connect as the identity store and authentication to sign in. I created a user and can sign in with that user by using my login url: https://<name>.awsapps.com/connect/login

**Comment by efh365** [comment]
Is this still an issue?

**Comment by dfw100** [comment]
@drewdresser could you please let us know if this is still an issue?

**Comment by khastation** [comment]
@drewdresser please reopen this issue if you're still facing this issue.
