### ISSUE TITLE
Add more language options for both transcription and translation

### ISSUE THREAD

**Issue by LucMacPaquet** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#16]
Hi, I added a third choice in the contact flow to add french transcription and set the attribute languageCode to fr-FR. Any idea why there is no french transcription in the CCP?

Also, where can I add french a an translation option?

Thanks

**Comment by efh365** [comment]
Hi, at the launch of the solution only two languages were supported. You will need to update the kvsTrigger lambda function and replace this line to accept fr-FR: https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/blob/master/source/kvs_trigger/index.js#L39

**Comment by LucMacPaquet** [comment]
Thanks for your answer. I'm wondering if there is a way to not hardcode the language... 
The different languages ​​need to be supported in which services? Transcribe of course, Comprehend, Translate?
Thanks
