### ISSUE TITLE
startLiveStreaming Failed

### ISSUE THREAD

**Issue by cheolulee** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#18]
sample UI console error code : 
**Uncaught Error: Failed to extract MediaRtpStats from RTCStatsReport for stream type audio_input**

my region : **ap-northeast-1(dokyo)**

sample UI shows this status:
**Name | Value
kvsTriggerLambdaResult | Success
languageCode | en-US
saveCallRecording | true
startStreamingAudioStatus | Success
transcribeCall | true**

Amazon Connect "Live Media Streaming" Enable Check Complete!!
**Please solve the error code.**

**Comment by efh365** [comment]
Hi cheolulee. That error has to do with the Call Control Panel loading on the webpage and is not related to this project directly. What browser are you using? Chrome and Firefox are the best ones to use with the CCP. Can you try on a different browser? Have you added the new URL to the your amazon connect console to allow it to load the CCP?

**Comment by cheolulee** [comment]
> Hi cheolulee. That error has to do with the Call Control Panel loading on the webpage and is not related to this project directly. What browser are you using? Chrome and Firefox are the best ones to use with the CCP. Can you try on a different browser? Have you added the new URL to the your amazon connect console to allow it to load the CCP?

I tried Chrome, firefox , edge....
Is there any other solution?

**Comment by cheolulee** [comment]
> Hi cheolulee. That error has to do with the Call Control Panel loading on the webpage and is not related to this project directly. What browser are you using? Chrome and Firefox are the best ones to use with the CCP. Can you try on a different browser? Have you added the new URL to the your amazon connect console to allow it to load the CCP?

![image](https://user-images.githubusercontent.com/74398702/99211674-33e07a00-280c-11eb-86d3-74533e8e5ca4.png)

**Comment by cheolulee** [comment]
> Hi cheolulee. That error has to do with the Call Control Panel loading on the webpage and is not related to this project directly. What browser are you using? Chrome and Firefox are the best ones to use with the CCP. Can you try on a different browser? Have you added the new URL to the your amazon connect console to allow it to load the CCP?

![image](https://user-images.githubusercontent.com/74398702/99216743-c20f2d00-2819-11eb-833d-9e8dd9cc3f03.png)
-> code edit

![image](https://user-images.githubusercontent.com/74398702/99216829-06023200-281a-11eb-8cc9-3ec9e4c987a4.png)
-> console log(internal server error)
I don't know this error

**Comment by miyelo** [comment]
Hi @efh365  
Thanks for the template but I have the same error using the "aiChatFlow"

![image](https://user-images.githubusercontent.com/19828958/99445990-f6e7b680-28e3-11eb-90b4-069d739a9c6f.png)

I think the problem is between the webSocket and the web-app because the tables in dynamo are being updated with the text

**Comment by cheolulee** [comment]
> Hi cheolulee. That error has to do with the Call Control Panel loading on the webpage and is not related to this project directly. What browser are you using? Chrome and Firefox are the best ones to use with the CCP. Can you try on a different browser? Have you added the new URL to the your amazon connect console to allow it to load the CCP?

The Amazon Region is Tokyo,
I am in Korea.
Is this a problem?
