### ISSUE TITLE
How can I get Outgoing Transcript of both agent and customer.

### ISSUE THREAD

**Issue by aman-appcino** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#20]
How can I get Outgoing Transcript of both agent and customer.

**Comment by efh365** [comment]
@aman-appcino can you clarify what you mean by an "outgoing transcript"?

**Comment by aman-appcino** [comment]
@efh365 
Hi I want to get real time transcript in case of Outbound call (agent to customer)
Right now the solution only providing this functionality in case of inbound calls only(customer to agent).

**Comment by dfw100** [comment]
@aman-appcino That is correct. The solution is designed to work only for Inbound call as described [here](https://docs.aws.amazon.com/solutions/latest/ai-powered-speech-analytics-for-amazon-connect/architecture.html) . You should be able to create a similar solution for outbound calling by using [StartOutboundVoiceContact](https://docs.aws.amazon.com/connect/latest/APIReference/API_StartOutboundVoiceContact.html) API  and reusing the components of this [solution](https://aws.amazon.com/solutions/implementations/ai-powered-speech-analytics-for-amazon-connect/).

**Comment by aman-appcino** [comment]
Thank you for your help and support @efh365 and @dfw100 .
I have found the solution for the same.

**Comment by dfw100** [comment]
Thanks @aman-appcino, I am glad you found the solution. I am closing this issue.

**Comment by dfw100** [comment]
@aman-appcino Also, if you got something generic, you are more than welcome to send a PR.
