### ISSUE TITLE
How can I get the real-time agent transcript?

### ISSUE THREAD

**Issue by Sarthak-Kulkarni** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#24]
@efh365 
The solution currently provides the real time transcript of the customer only. I tried multiple things but to no avail. Can you please tell me how to get the agent transcript as well? @efh365

**Comment by dfw100** [comment]
Hi Sarthak-Kulkarni, You need to enable streaming to and from the customer in the contact flow by using the Start Media Streaming block. Then you should see the audio stream to the customer being transcribed into the DDB for the ToCustomer audio stream.

**Comment by dfw100** [comment]
Hi Sarthak-Kulkarni, I am closing the issue since we haven't received a response yet. Please feel free to reopen to continue the discussion if issue still exists.

**Comment by Sarthak-Kulkarni** [comment]
Hi! Can you please provide more details. I am still very unclear on how to get the agent transcript. Please provide detailed steps.
