### ISSUE TITLE
How can i get agent side transciption? Currently I am only able to get customer transcription.

### ISSUE THREAD

**Issue by sourav31manjhi** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#25]
I want the agent transcription in Real-Time along with customer transcription.

**Comment by sourav31manjhi** [comment]
I want the agent transcription in Real-Time along with customer transcription.

**Comment by dfw100** [comment]
Hi sourav31manjhi, You need to enable streaming to and from the customer in the contact flow by using the Start Media Streaming block. Then you should see the audio stream to the customer being transcribed into the DDB for the ToCustomer audio stream.

**Comment by dfw100** [comment]
Hi sourav31manjhi, I am closing the issue since we haven't received a response yet. Please feel free to reopen to continue the discussion if issue still exists.
