### ISSUE TITLE
Chat with Translate doesn't work

### ISSUE THREAD

**Issue by cbgandhi** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#26]
Hi,

I tried to used Chat with Translate but when I click on Send Message button it throws following error in AWS SDK js:

Uncaught TypeError: agentChatSession.sendMessage is not a function

It seems the issue is with import conflicts of ChatJS and AWS SDK, as ChatJS comes with baked in AWS SDK version.

Can you please help?

Thank you.

**Comment by dfw100** [comment]
Hi Chintan, I am closing this issue as the demo is working for you now based on our conversation. Please feel free to reopen to continue the discussion if issue still exists.
