### ISSUE TITLE
How to get the real time agent transcript?

### ISSUE THREAD

**Issue by Sarthak-Kulkarni** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#27]
@dfw100 You provided some help in the #24 issue but I am still very unclear. Can you please provide detailed steps to get the real time agent transcript?
@dfw100

**Comment by khastation** [comment]
Hey Sarthak- relaying the message from #24, 
- You need to enable streaming to and from the customer in the contact flow by using the Start Media Streaming block. 
- Then you should see the audio stream to the customer being transcribed into the DDB for the ToCustomer audio stream.

Which part would you like a clarification on?

Here is some additional documentation to help set up media streaming in Amazon Connect:
https://docs.aws.amazon.com/connect/latest/adminguide/start-media-streaming.html

**Comment by Sarthak-Kulkarni** [comment]
Thanks, I got the agent transcript in the DDB table. Can you please help me to display the agent transcript on the front end in the same manner as the customer transcript?

**Comment by efh365** [comment]
Hi @Sarthak-Kulkarni, please refer to the suggestion on this thread to get the agent transcript on the frontend: https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/issues/19

**Comment by dfw100** [comment]
Please refer to the solution suggested on the thread  #19 to get the agent transcript on the frontend.
