### ISSUE TITLE
Transcriptions are not saved on S3 bucket

### ISSUE THREAD

**Issue by qt1211** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#3]
Hi,
For some reason, I got the first 3 transcripts saved on my S3 bucket (inside "transcripts" folder). However, none of the calls after that got transcripts saved. The real-time transcripts was still working. All audios were still saved in "recordings" folder. 
Could someone tell me where and which variables I need to check for this issues?
Here are some parameters I have set:
transcribeCall : TRUE
saveCallRecording: TRUE
CONSOLE_LOG_TRANSCRIPT_FLAG : TRUE
SAVE_PARTIAL_TRANSCRIPTS : TRUE
START_SELECTOR_TYPE : FRAGMENT_NUMBER
Thanks a lot.

**Comment by efh365** [comment]
Hi. The logic to upload the transcript to S3 is in the agentAssist.html file in the function writeTranscriptToS3(). At the end of the call the transcript is written to S3 as the contact attributes are being updated. Are you testing using the UX provided in this solution? If so, do you see any errors in the console when the call has ended?

**Comment by qt1211** [comment]
Oh, thanks. I found the issue. I changed the languageCode to en-AU for Australian accent, the Transcribe service does support en-AU but apparently the Comprehend does not. That's why I could see all transcripts but none are saved. To work around, I have added "en-AU" to fromLanguageDict.
Thanks for your help :)
