### ISSUE TITLE
Chat Translate not working

### ISSUE THREAD

**Issue by sachinjabshetty** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#30]
Hi,

I tried to used aichatflow for Chat with to Translate but it does nothing. chats dosent show on Translated Conversation and unable to send chat only native tool works. Sentiment is also not showing.

FYI - Voice works but translation is slow.

Please see the sample screenshot.

I am struggling from past few days to fix this but failed. 

Please need your help.

![Agent desktop AI](https://user-images.githubusercontent.com/86469612/123647178-7c055780-d845-11eb-9024-7b4866866168.PNG)

Thanks in advance.

**Comment by mcosicaws** [comment]
Could you please check if there were any errors in browser Developer Console?

Thanks,
Milos

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
