### ISSUE TITLE
[Feature] Adding more transcribe language

### ISSUE THREAD

**Issue by stevehouel** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#31]
[Feature] Suggestion

For now, only en-US and es-US are available on kvs_trigger function. I would like to add more compatible language in order improve that solution.

I would like to also translate current flow (agent and contact) into those languages and give choice to user when deploying the stack to choose one.

**Comment by angelacyu** [comment]
Hi @stevehouel, there are two places in AI Powered Speech Analytics to set the language code, in the function and contact flow. You can use any language code that is available here https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartStreamTranscription.html#API_streaming_StartStreamTranscription_RequestParameters

**Comment by angelacyu** [comment]
Please see this issue https://github.com/amazon-connect/ai-powered-speech-analytics-for-amazon-connect/issues/29 for complete instructions

**Comment by mcosicaws** [comment]
Closing due to no response, please feel free to re-open should you need any additional help.
