### ISSUE TITLE
Is it possible to transcribe both agent and customer voices? Or instead of customer's voice, could we transcribe agent's voice?

### ISSUE THREAD

**Issue by qt1211** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#4]

**Comment by efh365** [comment]
Hi, yes now you can stream the audio that the customer both says and hears. I have just updated the solution to account for this. https://docs.aws.amazon.com/connect/latest/adminguide/customer-voice-streams.html

You can follow the details on this README that tell you how to enable streaming. You will just need to add contact attributes saying which streaming to enable and you will need to update the Start Streaming block to stream in both directions. https://github.com/amazon-connect/amazon-connect-realtime-transcription#description
