### ISSUE TITLE
manifest-generator not available

### ISSUE THREAD

**Issue by ajay1976** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#5]
cd $deployment_dir/manifest-generator
npm install
node app.js

This is failing as there is no manifest-generator directory available and no app.js is available. is there any manually needs to be done to make it working?

**Comment by efh365** [comment]
Hi ajay, What are you trying to do specifically?

**Comment by kpx-dev** [comment]
Yea looks like it's missing the directory from here: 
https://github.com/awslabs/ai-powered-speech-analytics-for-amazon-connect/blob/master/deployment/build-s3-dist.sh#L217-L222

**Comment by efh365** [comment]
Thank you for pointing this out. I have just updated the solution and the manifest generator folder is there now.

**Comment by olegromanchuk** [comment]
The issue is still present - no "deployment/manifest-generator" folder. Solved with help of #37 however.
