### ISSUE TITLE
Not getting proper output for speech to text translation in dynamoDB

### ISSUE THREAD

**Issue by madmaxgorgon** [amazon-connect/ai-powered-speech-analytics-for-amazon-connect#7]
Hello I am trying to get the transcription from customer call. I was able to get the audio in S3 bucket. But at the time of real time transcription I am not getting exact output.
Ex. When I say "balance" or anything else it is just storing Recorded,Courted or where did.
It is not storing the actual speech.
Please reply this is kind of urgent

**Comment by khastation** [comment]
@madmaxgorgon I see this issue was created over a year ago, are you still facing the same issue?

**Comment by dfw100** [comment]
Please reopen the ticket should you need more help.
